version: '2'
services:
    aisles:
        depends_on: 
            - redis
        container_name: aisles
        build: .
        environment: 
            PORT: 5000
            REDIS_URL: redis://redis
            GUNICORN_CMD_ARGS: --reload --log-level debug
        ports: 
            - "5000:5000"
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"